# Generated by Django 2.0.3 on 2018-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180426_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Stéphanie', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Cloutier', max_length=64),
            preserve_default=False,
        ),
    ]
