version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - .:/app:Z
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
      - /media:/media
    depends_on:
      - web
  db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: common.env
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    volumes:
      - .:/app:Z
      - /media:/media

    links:
      - redis
    depends_on:
      - redis
  search:
    image: elasticsearch:5.4.3
    mem_limit: 1G
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ports:
      - '127.0.0.1:9200:9200'
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn saleor.wsgi -b 0.0.0.0:80"
    env_file: common.env
    depends_on:
      - db
      - redis
      - search
    # ports:
    #   - '8000:8000'
    volumes:
      - .:/app:Z
      - /static:/static
      - /media:/media
    expose:
      - "80"

volumes:
  postgres: