# Generated by Django 2.0.3 on 2018-05-24 18:56

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_required_attr_value_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='distributor',
            field=models.CharField(default='Text', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='EUR', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=django_prices.models.MoneyField(blank=True, currency='EUR', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.MoneyField(blank=True, currency='EUR', decimal_places=2, max_digits=12, null=True),
        ),
    ]
