# Generated by Django 2.0.3 on 2018-05-24 19:31

from django.db import migrations, models
import saleor.product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_auto_20180524_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='ean',
            field=models.CharField(default=1234567890123, max_length=13, validators=[saleor.product.validators.validate_ean]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_reference',
            field=models.CharField(default='AW8756', max_length=32),
            preserve_default=False,
        ),
    ]
