# Generated by Django 2.0.3 on 2018-05-25 16:49

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20180524_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_on',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
