# Generated by Django 2.0.3 on 2018-05-25 18:59

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_auto_20180525_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='available_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
