# Generated by Django 2.0.3 on 2018-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_auto_20180525_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.CharField(default='Wizards of the Coast', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_reference',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
