# Generated by Django 2.0.3 on 2018-05-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20180526_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product_reference',
            new_name='distributor_override',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='distributor',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_reference_override',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
