# Generated by Django 2.0.3 on 2018-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_auto_20180526_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_order',
            field=models.BooleanField(default=False),
        ),
    ]
