# Generated by Django 2.0.3 on 2018-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_product_on_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='content_override',
            field=models.TextField(blank=True, null=True),
        ),
    ]
