# Generated by Django 2.0.3 on 2018-06-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20180526_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product_content_override',
        ),
    ]
